[package]
edition = "2021"
name = "web-dash-builder"
version = "0.0.0"


[lib]
crate-type = ["cdylib"]

[[bin]]
name = "bin"
path = "src/main.rs"

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = ["napi4"] }
napi-derive = "2.12.2"
html-minifier = "4.0.0"
regex = "1.9.3"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.96"
zip = "0.6"
zip-extensions = "0.6"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
